name: register_broadcast_receiver
description: Flutter register broadcast receiver plugin.
version: 0.0.1
homepage: https://github.com/ag1le0/register_broadcast_receiver

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.hz.wu.register_broadcast_receiver.register_broadcast_receiver
        pluginClass: BroadcastReceiverPlugin
